# Generated by Django 3.2.7 on 2021-09-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STID', models.IntegerField()),
                ('tel', models.CharField(max_length=25)),
                ('college_year', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.CharField(max_length=10)),
                ('blood_type', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('Gpax', models.FloatField()),
            ],
        ),
    ]
