# Generated by Django 3.2.7 on 2021-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gpax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_type',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='college_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
