# Generated by Django 3.2.7 on 2021-09-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AlterField(
            model_name='course',
            name='semeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_term', to='regis.term'),
        ),
    ]
