# Generated by Django 3.2.7 on 2021-09-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0004_course_number_of_applicants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Number_of_Applicants',
            new_name='number_of_Applicants',
        ),
    ]
