# Generated by Django 3.2.7 on 2021-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0005_rename_number_of_applicants_course_number_of_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
