# Generated by Django 3.2.7 on 2021-10-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0007_auto_20210919_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semeter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_term', to='regis.term'),
        ),
    ]
